// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2hJmwjHeSiHv9LCdYTFpFE15qhP_h8pI',
    appId: '1:919049180578:web:b0f098534e9711812acefb',
    messagingSenderId: '919049180578',
    projectId: 'flutter-project-gl-b152a',
    authDomain: 'flutter-project-gl-b152a.firebaseapp.com',
    storageBucket: 'flutter-project-gl-b152a.firebasestorage.app',
    measurementId: 'G-JMRJNWVLYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBSUR2iJfxmpiWtcas3A7tFgaVvP1mtYc',
    appId: '1:919049180578:android:ac32c019456dab1f2acefb',
    messagingSenderId: '919049180578',
    projectId: 'flutter-project-gl-b152a',
    storageBucket: 'flutter-project-gl-b152a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGg5iVUJmqV0ajns_gt-vqdAKje0jISuE',
    appId: '1:919049180578:ios:279508910dab2e132acefb',
    messagingSenderId: '919049180578',
    projectId: 'flutter-project-gl-b152a',
    storageBucket: 'flutter-project-gl-b152a.firebasestorage.app',
    iosBundleId: 'com.example.devmobGestionrepas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGg5iVUJmqV0ajns_gt-vqdAKje0jISuE',
    appId: '1:919049180578:ios:279508910dab2e132acefb',
    messagingSenderId: '919049180578',
    projectId: 'flutter-project-gl-b152a',
    storageBucket: 'flutter-project-gl-b152a.firebasestorage.app',
    iosBundleId: 'com.example.devmobGestionrepas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2hJmwjHeSiHv9LCdYTFpFE15qhP_h8pI',
    appId: '1:919049180578:web:7a095c18cacdc5b02acefb',
    messagingSenderId: '919049180578',
    projectId: 'flutter-project-gl-b152a',
    authDomain: 'flutter-project-gl-b152a.firebaseapp.com',
    storageBucket: 'flutter-project-gl-b152a.firebasestorage.app',
    measurementId: 'G-JB6Q797V0H',
  );
}
